# Site settings
title: "PrestaShop Developers' blog"
email: build@prestashop.com
description: "Official blog for PrestaShop development straight from the core dev team."
baseurl: "/build.prestashop.com" # the subpath of your site, e.g. /blog/
url: "http://prestashop.github.io" # the base hostname & protocol for your site

permalink: /:categories/:title/


disqus_shortname: prestashopbuild

twitter_username: PrestaShop
github_username:  PrestaShop
instagram_username: prestacrew

# Build settings
markdown: kramdown
highlighter: pygments

exclude: ["bower.json", "Gemfile", "Gemfile.lock", "CNAME"]

sass:
    load_paths:
        - _sass
        - _bower_components
    style: compressed

# Page collection are used for how-tos pages
page_collections:
- theme:
    source: _howtos/theme
    icon: fa-text-width
- module:
    source: _howtos/module
    icon: fa-plug
- misc:
    source: _howtos/misc
    icon: fa-random
- upgrade:
    source: _howtos/upgrade
    icon: fa-refresh
