# Site settings
title: "PrestaShop Developers' blog"
email: build@prestashop.com
description: "Official blog for PrestaShop development straight from the core dev team."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dev.prestashop.com" # the base hostname & protocol for your site

twitter_username: PrestaShop
github_username:  PrestaShop
instagram_username: prestacrew

# Build settings
markdown: kramdown
highlighter: pygments

sass:
    load_paths:
        - _sass
        - _bower_components
    style: compressed
